export {
  WALLET_OWNERSHIP_CHAIN_IDS,
  WalletIdentityValidationError,
  formatWalletAccountId,
  parseEvmWalletAddress,
  parseSolanaWalletAddress,
  parseWalletAccountId,
  parseWalletAddress,
  parseWalletChainId,
  solanaWalletAddressBytes,
  walletNamespaceOf,
  type EvmWalletAddress,
  type SolanaWalletAddress,
  type WalletAccountId,
  type WalletAddress,
  type WalletIdentityValidationCode,
  type WalletNamespace,
  type WalletOwnershipChainId,
} from './domain/wallet-identity';
export {
  WALLET_OWNERSHIP_CHALLENGE_VERSION,
  WALLET_OWNERSHIP_MAX_TTL_MILLISECONDS,
  WALLET_OWNERSHIP_OPERATIONS,
  WALLET_OWNERSHIP_PROOF_KINDS,
  WalletOwnershipValidationError,
  createWalletOwnershipChallenge,
  hashWalletChallengeNonce,
  hashWalletOwnershipMessage,
  parseWalletChallengeId,
  parseWalletChallengeNonce,
  parseWalletDigest,
  parseWalletOrigin,
  parseWalletOwnershipChallengeRecord,
  parseWalletOwnershipOperation,
  parseWalletUri,
  verifyWalletOwnershipProof,
  type CreatedWalletOwnershipChallenge,
  type CreateWalletOwnershipChallengeInput,
  type Erc1271ContractSignatureVerifierPort,
  type Erc1271VerificationDecision,
  type EvmEip191WalletOwnershipProof,
  type EvmErc1271WalletOwnershipProof,
  type PublicWalletOwnershipChallenge,
  type SolanaEd25519WalletOwnershipProof,
  type WalletChallengeId,
  type WalletChallengeNonce,
  type WalletChallengeState,
  type WalletDigest,
  type WalletOrigin,
  type WalletOwnershipChallengeRecord,
  type WalletOwnershipOperation,
  type WalletOwnershipProof,
  type WalletOwnershipProofKind,
  type WalletOwnershipRejectionReason,
  type WalletOwnershipValidationCode,
  type WalletOwnershipVerificationOptions,
  type WalletOwnershipVerificationRequest,
  type WalletOwnershipVerificationResult,
  type WalletUri,
} from './domain/wallet-ownership-proof';
export { WalletsModule } from './wallets.module';
