export {
  SMART_LENDING_RECOMMENDATION_CLOCK,
  SYSTEM_SMART_LENDING_RECOMMENDATION_CLOCK,
  SmartLendingRecommendationService,
  SmartLendingRecommendationUnavailableError,
  type ReadSmartLendingRecommendationRequest,
  type SmartLendingRecommendationClock,
} from './application/smart-lending-recommendation.service';
export {
  FEE_AWARE_ALLOCATION_INPUT_READER,
  type FeeAwareAllocationInputReader,
  type FeeAwareAllocationInputs,
  type ReadFeeAwareAllocationInputsRequest,
} from './application/ports/fee-aware-allocation-input.port';
export {
  FEE_AWARE_ALLOCATION_COST_KINDS,
  FEE_AWARE_ALLOCATION_NETWORK_IDS,
  FEE_AWARE_ALLOCATION_POLICY_VERSION,
  FEE_AWARE_ALLOCATION_USD_SCALE,
  recommendFeeAwareAllocation,
  type FeeAwareAllocationCandidate,
  type FeeAwareAllocationCostKind,
  type FeeAwareAllocationCostsUsdMantissa,
  type FeeAwareAllocationExposurePolicy,
  type FeeAwareAllocationRecommendation,
  type FeeAwareAllocationRequest,
  type FeeAwareBridgeEstimate,
  type FeeAwareCandidateAssessment,
  type FeeAwareCandidateCalculation,
  type FeeAwareCandidateReason,
  type FeeAwareCapitalPosition,
  type FeeAwareCrossChainOptIn,
  type FeeAwareCrossChainPolicy,
  type FeeAwareLendingOpportunity,
  type FeeAwareOpportunityEvidence,
  type FeeAwarePositionDecision,
  type FeeAwareRiskAssessment,
  type FeeAwareRouteCostQuote,
} from './domain/fee-aware-allocation';
